### ISSUE TITLE
FS crashed at 1:25 PM PST 1/17/22  - crash logs

### ISSUE THREAD

**Issue by Metroid-Prime** [adirh3/Fluent-Search#462]
Not sure exactly what crashed it, but here's event viewer.   It's not an 00x00005 error so you hopefully you should have gotten crash logs. 
I was generally using FS and I was not in the settings panel, FYI.

```
Application: FluentSearch.exe
CoreCLR Version: 6.0.21.52210
.NET Version: 6.0.0
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentNullException: Value cannot be null. (Parameter 'key')
   at System.Collections.Generic.Dictionary`2.FindValue(TKey key)
   at Avalonia.Rendering.SceneGraph.SceneBuilder.FindExistingAncestor(Scene scene, IVisual visual) in C:\Git\Avalonia\src\Avalonia.Visuals\Rendering\SceneGraph\SceneBuilder.cs:line 130
   at Avalonia.Rendering.SceneGraph.SceneBuilder.Update(Scene scene, IVisual visual) in C:\Git\Avalonia\src\Avalonia.Visuals\Rendering\SceneGraph\SceneBuilder.cs:line 120
   at Avalonia.Rendering.DeferredRenderer.UpdateScene() in C:\Git\Avalonia\src\Avalonia.Visuals\Rendering\DeferredRenderer.cs:line 660
   at Avalonia.Rendering.DeferredRenderer.Paint(Rect rect) in C:\Git\Avalonia\src\Avalonia.Visuals\Rendering\DeferredRenderer.cs:line 206
   at Avalonia.Win32.WindowImpl.AppWndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in C:\Git\Avalonia\src\Windows\Avalonia.Win32\WindowImpl.AppWndProc.cs:line 370
   at Avalonia.Win32.WindowImpl.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in C:\Git\Avalonia\src\Windows\Avalonia.Win32\WindowImpl.WndProc.cs:line 33
```

```
Faulting application name: FluentSearch.exe, version: 0.9.90.991, time stamp: 0x61734cc9
Faulting module name: KERNELBASE.dll, version: 10.0.19041.1466, time stamp: 0xe01c7650
Exception code: 0xe0434352
Fault offset: 0x0000000000034f69
Faulting process id: 0x2170
Faulting application start time: 0x01d80bd649cbb987
Faulting application path: D:\Applications\Fluent Search\FluentSearch.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: 3dabbd39-13b4-4401-862a-7da5158776ea
Faulting package full name: 
Faulting package-relative application ID
```

```
Faulting application name: FluentSearch.exe, version: 0.9.90.991, time stamp: 0x61734cc9
Faulting module name: KERNELBASE.dll, version: 10.0.19041.1466, time stamp: 0xe01c7650
Exception code: 0xc000041d
Fault offset: 0x0000000000034f69
Faulting process id: 0x2170
Faulting application start time: 0x01d80bd649cbb987
Faulting application path: D:\Applications\Fluent Search\FluentSearch.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: b824b2ff-6ece-4bc3-962f-621261cf33fa
Faulting package full name: 
Faulting package-relative application ID: 
```

**Comment by adirh3** [comment]
Thanks @Metroid-Prime this is a pretty rare crash I see it happen once every few days in nightly for a while now.
If you can somehow repro that, it would be really helpful.

**Comment by Metroid-Prime** [comment]
k I'll keep an eye out. In the meantime, I will close this and re-open.   It's hard to tell though which crash is related to what but if I see similar fault offsets, i'll let you know.
