### ISSUE TITLE
Indexer is crashing due to invalid Unicode code point

### ISSUE THREAD

**Issue by green-s** [adirh3/Fluent-Search#487]
**Describe the bug**
At some point in the past few weeks the indexer service started crashing on launch. According to the stack trace in the event log this is because a string (filename?) has an invalid Unicode code point.

```
Category: Blast.IndexerService.Worker
EventId: 0

Fluent Search indexer crashed

Exception: 
System.ArgumentException: String contains invalid Unicode code points. (Parameter 'strInput')
   at System.Globalization.Normalization.ValidateArguments(String strInput, NormalizationForm normalizationForm)
   at System.Globalization.Normalization.IcuNormalize(String strInput, NormalizationForm normalizationForm)
   at Blast.Core.StringExtensions.RemoveDiacritics(String text) in D:\a\1\s\Blast.Core\StringExtensions.cs:line 18
   at Blast.IndexerService.SQLite.CommandUtils.UpdateCreateCommandParameters(String name, String fullName, DateTime lastAccessTime, UInt64 size, Boolean isDirectory, String extension) in D:\a\1\s\Blast.IndexerService\SQLite\CommandUtils.cs:line 59
   at Blast.IndexerService.SqliteFileIndexer.IndexAllDrives(Boolean force, List`1 indexPaths, String[] ignorePaths, CancellationToken cancellationToken) in D:\a\1\s\Blast.IndexerService\SqliteFileIndexer.cs:line 143
   at Blast.IndexerService.Worker.IndexFileLoop(CancellationToken stoppingToken) in D:\a\1\s\Blast.IndexerService\Worker.cs:line 200
   at Blast.IndexerService.Worker.ExecuteAsync(CancellationToken stoppingToken) in D:\a\1\s\Blast.IndexerService\Worker.cs:line 117
```

**Desktop:**
 - Windows 11 Pro 21H2
 - Fluent Search Version 0.9.90.9998

**Comment by adirh3** [comment]
Thanks for reporting it @green-s!

**Comment by adirh3** [comment]
@green-s Do you have `Send crash diagnostics` disabled?

**Comment by adirh3** [comment]
Pushed a fix for it in the latest stable, thanks again for posting it.
