### ISSUE TITLE
Not starting on windows 11 insider

### ISSUE THREAD

**Issue by chupi33** [adirh3/Fluent-Search#581]
Hello

**Describe the bug**

After installation and launching (and not starting)
4 errors in Windows Event Log Service

```
Application: FluentSearch.exe
CoreCLR Version: 6.0.422.16404
.NET Version: 6.0.4
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at Blast.Core.FluentSearchLanguage.GetLanguageName(FluentSearchLanguages languages) in D:\a\1\s\Blast.Core\FluentSearchLanguage.cs:line 32
   at Blast.Program.Main(String[] args) in D:\a\1\s\Blast\Program.cs:line 202
```
```
Nom de l’application défaillante FluentSearch.exe, version : 0.9.91.66, horodatage : 0x622f78e0
Nom du module défaillant : KERNELBASE.dll, version : 10.0.22616.1, horodatage : 0xec07489e
Code d’exception : 0xe0434352
Décalage d’erreur : 0x000000000008fa7c
ID du processus défaillant : 0x0x137C
Heure de début de l’application défaillante : 0x0x1D864F5E97CDB9B
Chemin d’accès de l’application défaillante : C:\Program Files\Fluent Search\FluentSearch.exe
Chemin d’accès du module défaillant: C:\WINDOWS\System32\KERNELBASE.dll
ID de rapport : d38227dc-b54b-445a-aa72-422612506312
Nom complet du package défaillant : 
ID de l’application relative au package défaillant : 
```

```
Application: FluentSearch.exe
CoreCLR Version: 6.0.422.16404
.NET Version: 6.0.4
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at Blast.Core.FluentSearchLanguage.GetLanguageName(FluentSearchLanguages languages) in D:\a\1\s\Blast.Core\FluentSearchLanguage.cs:line 32
   at Blast.Core.FluentSearchLanguage.get_SelectedLanguageId() in D:\a\1\s\Blast.Core\FluentSearchLanguage.cs:line 12
   at Blast.Program.Main(String[] args) in D:\a\1\s\Blast\Program.cs:line 207
```

```
Nom de l’application défaillante FluentSearch.exe, version : 0.9.91.66, horodatage : 0x622f78e0
Nom du module défaillant : KERNELBASE.dll, version : 10.0.22616.1, horodatage : 0xec07489e
Code d’exception : 0xe0434352
Décalage d’erreur : 0x000000000008fa7c
ID du processus défaillant : 0x0x2734
Heure de début de l’application défaillante : 0x0x1D864F5EA8E0ADE
Chemin d’accès de l’application défaillante : C:\Program Files\Fluent Search\FluentSearch.exe
Chemin d’accès du module défaillant: C:\WINDOWS\System32\KERNELBASE.dll
ID de rapport : 1fc53310-d07a-4149-be7a-4910e5f7e0fd
Nom complet du package défaillant : 
ID de l’application relative au package défaillant : 
```

**Desktop :**
- Windows 11 Version: 22H2 22616.1 (insider)
- Fluent Search Version: 0.9.91.66 May 10, 2022 at 20:34

as you can imagine i don't speak english 😥 ... sorry 😉
an i know it's insider so ... 

thank you

**Comment by adirh3** [comment]
Hey @chupi33, thanks for reporting this.
I will fix it in today's update, if youd like to run it now you can you do the following -
1. Open Fluent Search installed folder in CMD
2. Run `FluentSearch.exe English`
3. The app should open, go to Settings -> System, change language

Let me know if it works out for you.

**Comment by chupi33** [comment]
Hello

It works !!!! I can't change language in French after start but it doesn't matter

Do you want i keep the issue open until you publish today's update ?

thanks

**Comment by adirh3** [comment]
> Hello
> 
> It works !!!! I can't change language in French after start but it doesn't matter
> 
> Do you want i keep the issue open until you publish today's update ?
> 
> thanks

Thanks for the update, I will close it once it's fixed.
French is currently not translated, before it was a auto translate.
If you'd like to help with translations please join the Discord server https://discord.gg/W2EuWvD6GD
