### ISSUE TITLE
Fluent Search  is not  building file index

### ISSUE THREAD

**Issue by gman414** [adirh3/Fluent-Search#641]
Describe the bug: Fluent Search Version 0.9.92.11 and up to Version 0.9.92.18 
 is not building file index for any of the selected indexed paths. 
This happens on both EXE and APPX versions.

To Reproduce:

1)	Once FS is updated to or installed one of the FS versions stated above.
2)	Nothing gets indexed i.e when search for files does not produce the search results
3)	No search result is produced
      i.	Even id both FS File Indexer and Windows FluentSearch.FileIndexer seems to be running
![image](https://user-images.githubusercontent.com/110206456/182007276-e00e4750-8bc2-414a-b525-7e40f7cc93ce.png)

![image](https://user-images.githubusercontent.com/110206456/182007310-8c3569b7-44ec-43e6-8a06-803b4c817d9f.png)

      ii.	Even if both services are stopped and restarted
      iii.	Even if the FS service is uninstalled and reinstalled.
4)	At times both FS File Indexer and Windows FluentSearch.FileIndexer seems to have stopped.
5)	On the search bar, the tool tip displays that Fluent Search is indexing paths (in this D:\)
but this keeps going on an on for an indefinite amount of time. But it does not display the searched files .
![image](https://user-images.githubusercontent.com/110206456/182007242-c3c1f3d6-22cd-4330-b9b5-8ef611077e81.png)

Desktop:
Windows 10 Pro , 21H2 (OS build 19044.1826)
Fluent Search Version [0.9.92.11 to 0.9.92.18]

Note: Currently I am using Fluent Search Version 0.9.92.1
Indexing seems to work fine on this version.

![image](https://user-images.githubusercontent.com/110206456/182007719-799fd03a-eb4c-427c-b9b2-bd2977745a68.png)

**Eventvwr**

Log Name:      Application
Source:        FluentSearch
Date:          31/07/2022 05:28:38
Event ID:      0
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      DESKTOP-VK09LMC
Description:
Category: Blast.IndexerService.Worker
EventId: 0

Fluent Search indexer crashed

Exception: 
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'index')
   at System.Linq.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument)
   at System.Linq.Enumerable.ElementAt[TSource](IEnumerable`1 source, Int32 index)
   at Blast.IndexerService.Ntfs.MftReader.GetNodeFullNameCore(UInt32 nodeIndex, Int32 nodeLinkIndex) in D:\a\1\s\Blast.IndexerService\Ntfs\NtfsReader.Algorithms.cs:line 58
   at Blast.IndexerService.Ntfs.MftReader.NodeWrapper.get_FullName() in D:\a\1\s\Blast.IndexerService\Ntfs\MftReader.cs:line 464
   at Blast.IndexerService.SqliteFileIndexer.IndexAllDrives(String databaseFileName, IEnumerable`1 indexPaths, List`1 ignorePaths, List`1 contentIndexPaths, CancellationToken cancellationToken) in D:\a\1\s\Blast.IndexerService\SqliteFileIndexer.cs:line 89
   at Blast.IndexerService.Worker.IndexFileLoop() in D:\a\1\s\Blast.IndexerService\Worker.cs:line 281
   at Blast.IndexerService.Worker.ExecuteAsync(CancellationToken stoppingToken) in D:\a\1\s\Blast.IndexerService\Worker.cs:line 139
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="FluentSearch" />
    <EventID Qualifiers="0">0</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2022-07-30T21:28:38.5694175Z" />
    <EventRecordID>161506</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>DESKTOP-VK09LMC</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Category: Blast.IndexerService.Worker
EventId: 0

Fluent Search indexer crashed

Exception: 
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'index')
   at System.Linq.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument)
   at System.Linq.Enumerable.ElementAt[TSource](IEnumerable`1 source, Int32 index)
   at Blast.IndexerService.Ntfs.MftReader.GetNodeFullNameCore(UInt32 nodeIndex, Int32 nodeLinkIndex) in D:\a\1\s\Blast.IndexerService\Ntfs\NtfsReader.Algorithms.cs:line 58
   at Blast.IndexerService.Ntfs.MftReader.NodeWrapper.get_FullName() in D:\a\1\s\Blast.IndexerService\Ntfs\MftReader.cs:line 464
   at Blast.IndexerService.SqliteFileIndexer.IndexAllDrives(String databaseFileName, IEnumerable`1 indexPaths, List`1 ignorePaths, List`1 contentIndexPaths, CancellationToken cancellationToken) in D:\a\1\s\Blast.IndexerService\SqliteFileIndexer.cs:line 89
   at Blast.IndexerService.Worker.IndexFileLoop() in D:\a\1\s\Blast.IndexerService\Worker.cs:line 281
   at Blast.IndexerService.Worker.ExecuteAsync(CancellationToken stoppingToken) in D:\a\1\s\Blast.IndexerService\Worker.cs:line 139
</Data>
  </EventData>
</Event>

**Comment by adirh3** [comment]
@gman414 thanks a lot for reporting it, it's much appreciated!
Will try to fix it in today's update.

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.92.19                                         . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe

**Comment by gman414** [comment]
> This issue has been potentially fixed in version 0.9.92.19 . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe

@adirh3  Issue has been resolved. Thank you for your quick action.

**Comment by adirh3** [comment]
> > This issue has been potentially fixed in version 0.9.92.19 . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe
> 
> @adirh3 Issue has been resolved. Thank you for your quick action.

Thanks for updating @gman414! I would appreciate if you can let me know as soon as possible if you notice any other issues with the indexer or file searching.
I plan to push the indexer changes to the stable feed this week.
