### ISSUE TITLE
press `enter` in `C#` block in tasks will cause FS crash

### ISSUE THREAD

**Issue by u-Sir** [adirh3/Fluent-Search#699]
**Describe the bug**
click on textbox and press `enter` in `C#` block in tasks will cause FS crash

**To Reproduce**
1. Go to `tasks`
2. create a `C#` block
3. click on textbox and press `enter`

**Desktop (please complete the following information):**
 - Windows 11 Version: 22H2
 - Fluent Search Version 0.9.92.58

**Additional context**
```
Application: FluentSearch.exe
CoreCLR Version: 7.0.22.51805
.NET Version: 7.0.0
Description: The process was terminated due to an unhandled exception.
Exception Info: System.MethodAccessException: Attempt by method 'AvaloniaEdit.Editing.TextArea.PerformTextInput(System.String)' to access method 'Avalonia.Input.TextInputEventArgs..ctor()' failed.
   at AvaloniaEdit.Editing.TextArea.PerformTextInput(String text)
   at AvaloniaEdit.Editing.EditingCommandHandler.OnEnter(Object target, ExecutedRoutedEventArgs args)
   at AvaloniaEdit.RoutedCommandBinding.DoExecuted(Object sender, ExecutedRoutedEventArgs e)
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at AvaloniaEdit.RoutedCommand.ExecutedEventHandler(IRoutedCommandBindable control, ExecutedRoutedEventArgs args)
   at Avalonia.Interactivity.EventRoute.RaiseEventImpl(RoutedEventArgs e)
   at Avalonia.Interactivity.Interactive.RaiseEvent(RoutedEventArgs e)
   at AvaloniaEdit.RoutedCommand.Execute(Object parameter, IInputElement target)
   at AvaloniaEdit.RoutedCommand.System.Windows.Input.ICommand.Execute(Object parameter)
   at AvaloniaEdit.Editing.TextAreaInputHandler.TextAreaOnKeyDown(Object sender, KeyEventArgs keyEventArgs)
   at Avalonia.Interactivity.Interactive.<AddHandler>g__InvokeAdapter|4_0[TEventArgs](Delegate baseHandler, Object sender, RoutedEventArgs args)
   at Avalonia.Interactivity.EventRoute.RaiseEventImpl(RoutedEventArgs e)
   at Avalonia.Interactivity.Interactive.RaiseEvent(RoutedEventArgs e)
   at Avalonia.Input.KeyboardDevice.ProcessRawEvent(RawInputEventArgs e)
   at Avalonia.Controls.TopLevel.HandleInput(RawInputEventArgs e)
   at Avalonia.Win32.WindowImpl.AppWndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Avalonia.Win32.WindowImpl.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   at Blast.Program.Main(String[] args) in D:\a\1\s\Blast\Program.cs:line 301
```

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.92.60                                         . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe
