### ISSUE TITLE
FS crashed randomly when launching with IME

### ISSUE THREAD

**Issue by u-Sir** [adirh3/Fluent-Search#717]
**Describe the bug**
FS crashed randomly when launching with IME

**To Reproduce**
Steps to reproduce the behavior, not 100% trigger:
1. launch search window
2. switch to IME, e.g. `wubi`, typing anything to search
3. relaunch search window
4. now the default IME is `wubi`, quick typing anything to search
5. delete characters and quick typing anything to search again

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Windows 11 Version: 22h2
 - Fluent Search Version 0.9.92.61

**Additional context**
```
错误应用程序名称: FluentSearch.exe，版本: 0.9.92.61，时间戳: 0x634eda42
错误模块名称: KERNELBASE.dll，版本: 10.0.22621.755，时间戳: 0x19d26491
异常代码: 0xe0434352
错误偏移量: 0x000000000009039c
错误进程 ID: 0x0x4C20
错误应用程序启动时间: 0x0x1D9007CF824CAE8
错误应用程序路径: C:\Program Files\Fluent Search\FluentSearch.exe
错误模块路径: C:\Windows\System32\KERNELBASE.dll
报告 ID: 5102f834-24b4-401a-a0b9-5d7b49bec0f5
错误程序包全名: 
错误程序包相对应用程序 ID: 
```

```
Application: FluentSearch.exe
CoreCLR Version: 7.0.22.51805
.NET Version: 7.0.0
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentOutOfRangeException: Index and length must refer to a location within the string. (Parameter 'length')
   at Avalonia.Controls.Presenters.TextPresenter.CreateTextLayout()
   at Avalonia.Controls.Presenters.TextPresenter.get_TextLayout()
   at Avalonia.Controls.Presenters.TextPresenter.GetCharacterHitFromTextPosition(Int32 textPosition)
   at Avalonia.Controls.Presenters.TextPresenter.OnPreeditTextChanged(String oldValue, String newValue)
   at Avalonia.Animation.Animatable.OnPropertyChangedCore(AvaloniaPropertyChangedEventArgs change)
   at Avalonia.AvaloniaObject.RaisePropertyChanged[T](AvaloniaPropertyChangedEventArgs`1 change)
   at Avalonia.AvaloniaObject.SetAndRaise[T](AvaloniaProperty`1 property, T& field, T value)
   at Avalonia.Controls.Presenters.TextPresenter.set_PreeditText(String value)
   at Avalonia.Controls.TextBoxTextInputMethodClient.SetPreeditText(String text)
   at Avalonia.Win32.Input.Imm32InputMethod.CompositionChanged()
   at Avalonia.Win32.WindowImpl.AppWndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Avalonia.Win32.WindowImpl.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   at Blast.Program.Main(String[] args) in D:\a\1\s\Blast\Program.cs:line 301
```

**Comment by u-Sir** [comment]
new crashed info
```
Application: FluentSearch.exe
CoreCLR Version: 7.0.22.51805
.NET Version: 7.0.0
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
Stack:
   at SQLitePCL.SQLite3Provider_e_sqlite3+NativeMethods.sqlite3_step(SQLitePCL.sqlite3_stmt)
   at SQLitePCL.SQLite3Provider_e_sqlite3+NativeMethods.sqlite3_step(SQLitePCL.sqlite3_stmt)
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(System.Data.CommandBehavior)
   at Blast.FileSearchApp.WindowsSearcher.FluentSearch+<SearchQuery>d__32.MoveNext()
   at Blast.FileSearchApp.FileSearchApp+<SearchAsync>d__26.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.__Canon ByRef)
   at Blast.FileSearchApp.FileSearchApp+<SearchAsync>d__26.System.Collections.Generic.IAsyncEnumerator<Blast.Core.Interfaces.ISearchResult>.MoveNextAsync()
   at Blast.BlastSearch.Logic.SearchTimeScheduler+<SearchGroup>d__7.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[Blast.BlastSearch.Logic.SearchTimeScheduler+<SearchGroup>d__7, Blast.BlastSearch, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]](<SearchGroup>d__7 ByRef)
   at Blast.BlastSearch.Logic.SearchTimeScheduler.SearchGroup(Blast.BlastSearch.Logic.SearchApplicationGroup, System.Threading.Channels.ChannelWriter`1<Blast.Core.Interfaces.ISearchResult>, System.Threading.CancellationToken)
   at System.Threading.Tasks.Task`1[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(System.Threading.Thread, System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef, System.Threading.Thread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool+WorkerThread.WorkerThreadStart()
```
